#!/usr/bin/env python3
import sys

def main():

    # ensure proper usage
    if len(sys.argv) != 1:
        sys.exit("Usage: ./tweets twitter_user_name")

    return 0

if __name__ == "__main__":
    main()
