#!/usr/bin/env python3
import sys
import helpers

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @twitter_user_name")

    # get tweets
    tweets = helpers.get_user_timeline(sys.argv[1])
    if tweets == None:
        sys.exit("Please provide a proper Twitter user name.")


    # initialize Analyzer

    # analyze tweets

    return 0

if __name__ == "__main__":
    main()
